spring:
  application:
    version: @project.version@
    name: message
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}/message
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 20
      minimum-idle: 2
      idle-timeout: 10000
      connection-timeout: 15000
      register-mbeans: true
      connection-test-query: select 1 from dual
      leak-detection-threshold: 30000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
ricciliao:
  x:
    common:
      time-zone: GMT+8
    log:
      executor:
        enable: true
    cache-consumer:
      consumer: message
      operation-list:
        - store: code
          store-class-name: ricciliao.message.cache.pojo.MessageCodeCacheDto

